import { StateResponse } from "./api-types";

// Builds a plain-text situation report a health official could actually read,
// print, or forward — the kind of artifact a decision-support tool needs to
// produce to be useful beyond the dashboard screen itself.
export function generateSituationReport(data: StateResponse): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 16).replace("T", " ");

  lines.push("MEDWATCH — SHORTAGE SITUATION REPORT");
  lines.push(`Generated: ${now} UTC · Simulated day ${data.simDay}`);
  lines.push("=".repeat(60));
  lines.push("");

  const regional = data.regionalRisks.filter((r) => r.riskLevel === "regional");
  const isolated = data.regionalRisks.filter((r) => r.riskLevel === "isolated");
  const watch = data.regionalRisks.filter((r) => r.riskLevel === "watch");

  lines.push(`SUMMARY: ${regional.length} regional risk(s), ${watch.length} emerging pattern(s), ${isolated.length} isolated event(s).`);
  lines.push("");

  if (regional.length > 0) {
    lines.push("REGIONAL RISKS (multiple facilities, correlated pattern)");
    lines.push("-".repeat(60));
    for (const r of regional) {
      lines.push(`* ${r.medicineName} — ${r.clusterName} (score ${r.score}/100)`);
      for (const f of r.facilitiesAtRisk) {
        lines.push(`    - ${f.facilityName}: stockout projected in ${f.daysToStockout} day(s)`);
      }
      for (const reason of r.reasoning) lines.push(`    Reasoning: ${reason}`);
      lines.push("");
    }
  }

  if (isolated.length > 0) {
    lines.push("ISOLATED EVENTS (single facility, no corroborating pattern)");
    lines.push("-".repeat(60));
    for (const r of isolated) {
      lines.push(`* ${r.medicineName} — ${r.facilitiesAtRisk[0]?.facilityName ?? r.clusterName} (score ${r.score}/100)`);
    }
    lines.push("");
  }

  if (data.suggestions.length > 0) {
    lines.push("RECOMMENDED REDISTRIBUTION");
    lines.push("-".repeat(60));
    for (const s of data.suggestions) {
      lines.push(`* Move ${s.suggestedQuantity} ${s.medicineName} from ${s.fromFacilityName} to ${s.toFacilityName} (urgency ${s.urgencyScore}/100, ${s.distance} km)`);
      if (s.withoutTransferDays !== null) {
        lines.push(`    Impact: extends cover from ${s.withoutTransferDays}d to ~${s.withTransferDays}d`);
      }
    }
    lines.push("");
  }

  lines.push("=".repeat(60));
  lines.push("Generated by MedWatch — heuristic forecasts on simulated data; confirm before acting.");

  return lines.join("\n");
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
